################################################################################
# UNIVERSIDADE FEDERAL DE CATALÃO (UFCAT)
# WANDERLEI MALAQUIAS PEREIRA JUNIOR,                  ENG. CIVIL / PROF (UFCAT)
# MARCOS NAPOLEÃO RABELO,                              ENG. CIVIL / PROF (UFCAT)
# DAVIDSON DE OLIVEIRA FRANÇA JUNIOR,                    ENG. CIVIL / PROF (UNA)
# GABRIEL BERNARDES CARVALHO,                                 ENG. CIVIL (UFCAT)
# JOSÉ VITOR CARVALHO SILVA,                                  ENG. CIVIL (UFCAT)
# MURILO CARNEIRO RODRIGUES,                                  ENG. CIVIL (UFCAT)
# Mexi aqui
################################################################################


################################################################################
# DESCRIÇÃO ALGORITMO:
# BIBLIO. DE USO COMUM PARA ALGORITMOS DE ELEMENTOS FINITOS DESENVOL-
# VIDA PELO GRUPO DE PESQUISA E ESTUDOS EM ENGENHARIA (GPEE)
################################################################################


################################################################################
# BIBLIOTECAS NATIVAS PYTHON
import numpy as np

################################################################################
# BIBLIOTECAS DESENVOLVEDORES GPEE
import FINITO_COMMON_LIBRARY as FINITO_CL

# PROGRAMA DE ELEMENTOS FINITO PARA BARRAS COM DOIS NÓS (1 NÓ POR EXTREMIDADE)
def MEF1D(**kwargs):
    """ 
    This function performs structural analysis of bars with 2 nodes (1 at each end)
    
    Input:
    All inputs kwargs arguments type
    FILENAME: Structural dataset (.txt extension)
    DICTIONARY: Structural dataset (Python dictionary)

    Output:
    RESULTS: Structural analysis results by element (Python dictionary)
    """
    # Read input file
    FILENAME = kwargs.get('FILENAME')
    DICTIONARY = kwargs.get('DICTIONARY')
    if FILENAME:
        TYPE_SOLUTION, TYPE_ELEMENT, N_NODES, N_MATERIALS, N_SECTIONS, N_ELEMENTS, N_DOFPRESCRIPTIONS, N_ELEMENTSLOADED, N_NODESLOADED, N_SPRINGS, COORDINATES, ELEMENTS, MATERIALS, SECTIONS, PRESCRIPTIONS, ELEMENT_EXTERNAL_LOAD, NODAL_EXTERNAL_LOAD, SPRINGS = FINITO_CL.GET_VALUE_FROM_TXT_MEF1D_FINITO(FILENAME)
    else:
        TYPE_SOLUTION, TYPE_ELEMENT, N_NODES, N_MATERIALS, N_SECTIONS, N_ELEMENTS, N_DOFPRESCRIPTIONS, N_ELEMENTSLOADED, N_NODESLOADED, N_SPRINGS, COORDINATES, ELEMENTS, MATERIALS, SECTIONS, PRESCRIPTIONS, ELEMENT_EXTERNAL_LOAD, NODAL_EXTERNAL_LOAD, SPRINGS = FINITO_CL.GET_VALUE_FROM_DICT_MEF1D_FINITO(DICTIONARY)
    # Creating the Algorithm's Internal Parameters
    N_DOFSNODE, N_NODESELEMENT, DOFS_ACTIVE, DOFS_LOCAL, AUX_1, AUX_2, N_DOFSELEMENT = FINITO_CL.INDEX_ASSEMBLY(TYPE_ELEMENT)
    # GLOBAL DOF ASSEMBLY
    DOF_GLOBALNODAL = FINITO_CL.DOF_GLOBAL_ASSEMBLY(TYPE_ELEMENT, N_DOFSNODE, N_NODES)
    # DOFS TOTALS, PRESCRIPTIONS AND FREES
    DOF_GLOBAL, N_DOFSGLOBAL = FINITO_CL.TOTAL_DEGREE_FREEDOM(N_DOFSNODE, N_NODES)
    DOF_PRESCRIPTIONS, DOF_PRESCRIPTIONSVALUE, N_DOFSPRESCRIPTIONS = FINITO_CL.PRESCRIPTIONS_DEGREE_FREEDOM(PRESCRIPTIONS, DOF_GLOBALNODAL, N_DOFSNODE)
    DOF_FREE, N_DOFSFREE = FINITO_CL.FREE_DEGREE_FREEDOM(DOF_PRESCRIPTIONS, DOF_GLOBAL)
    # NODAL LOAD CONTRIBUTION
    DOF_NODALFORCE = FINITO_CL.CONTRIBUTION_NODAL_EXTERNAL_LOAD(NODAL_EXTERNAL_LOAD, N_DOFSGLOBAL, DOF_GLOBALNODAL)
    F_EXT = DOF_NODALFORCE
    # GLOBAL STIFFNES AND INTERNAL LOADS ASSEMBLY
    K_G = np.zeros((N_DOFSGLOBAL, N_DOFSGLOBAL))
    F_INT = np.zeros((N_DOFSGLOBAL, 1))
    # HINGED ELEMENTS
    HINGES = FINITO_CL.HINGED_PROPERTIES(ELEMENTS)
    for I_ELEMENT in range(N_ELEMENTS):
        # ELEMENTS PROPERTIES
        MATERIAL_IELEMENT = FINITO_CL.MATERIALS_PROPERTIES_0(ELEMENTS, MATERIALS, I_ELEMENT, AUX_1)
        SECTION_IELEMENT = FINITO_CL.GEOMETRIC_PROPERTIES_0(COORDINATES, ELEMENTS, SECTIONS, I_ELEMENT, AUX_2)
        # ELEMENT STIFFNESS LOCAL AXIS
        K_IELEMENT = FINITO_CL.ELEMENT_STIFFNESS_0(TYPE_ELEMENT, SECTION_IELEMENT, MATERIAL_IELEMENT, HINGES[I_ELEMENT, :])
        # ROTATION
        R_IELEMENT = FINITO_CL.ELEMENT_ROTATION(TYPE_ELEMENT, SECTION_IELEMENT)
        # ELEMENT STIFFNESS GLOBAL AXIS
        K_IELEMENTGLOBAL = np.dot(np.dot(np.transpose(R_IELEMENT), K_IELEMENT), R_IELEMENT)
        # GOBAL DOF I_ELEMENT
        DOF_GLOBALIELEMENT = FINITO_CL.GLOBAL_DOF_ELEMENT(N_NODESELEMENT, N_DOFSNODE, DOF_GLOBALNODAL, ELEMENTS, I_ELEMENT)
        # GLOBAL STIFFNESS
        K_GCONTRIBUITION = FINITO_CL.GLOBAL_STIFFNESS(N_DOFSGLOBAL, DOF_GLOBALIELEMENT, K_IELEMENTGLOBAL)
        K_G = K_G + K_GCONTRIBUITION
    # SPRING CONTRIBUTION
    if N_SPRINGS > 0:
        SPRING_INDEX, SPRING_VALUES = FINITO_CL.SPRING_CONTRIBUTION(N_DOFSNODE, SPRINGS, N_SPRINGS)
        for K_COUNT in range(N_SPRINGS):
            SPRING_VALUE = SPRING_VALUES[K_COUNT]
            INDEX_DOF = SPRING_INDEX[K_COUNT]
            K_G[INDEX_DOF, INDEX_DOF] = K_G[INDEX_DOF, INDEX_DOF] + SPRING_VALUE
    # DISPLACEMENT SOLUTION: CONDENSE PROCEDURE
    if TYPE_SOLUTION == 0:
        # CONDENSE DISPLACEMENTS, FORCES AND STIFFNESS MATRIX
        U_PP = FINITO_CL.CONDENSE_PRESCRIBED_GLOBAL_DISPLACEMENT(DOF_PRESCRIPTIONSVALUE, N_DOFSPRESCRIPTIONS)
        F_FF = FINITO_CL.CONDENSE_FREE_GLOBAL_FORCES(F_EXT, DOF_FREE, N_DOFSFREE)
        K_FF = FINITO_CL.CONDENSE_GLOBAL_FREE_STIFFNESS(K_G, DOF_FREE, N_DOFSFREE)
        K_PF = FINITO_CL.CONDENSE_PRESCRIBED_FREE_GLOBAL_STIFFNESS(K_G, DOF_FREE, N_DOFSFREE, DOF_PRESCRIPTIONS, N_DOFSPRESCRIPTIONS)
        # SOLUTION
        K_FFINVERSE = np.linalg.pinv(K_FF, rcond=1e-15)
        U_FF = np.dot(K_FFINVERSE, F_FF - np.dot(np.transpose(K_PF), U_PP))
        U_G = FINITO_CL.ASSEMBLY_TOTAL_DISPLACEMENT(U_FF, U_PP, N_DOFSGLOBAL, DOF_PRESCRIPTIONS, DOF_FREE)
    # DISPLACEMENT SOLUTION: ZERO AND ONE PROCEDURE
    elif TYPE_SOLUTION == 1:
        pass
    # INTERNAL LOADS
    # FRAME DIVISION
    DIV = 11 
    # START EMPTY DICTIONARY RESULTS
    RESULTS = [{'X': np.empty(DIV), 'UX': np.empty(DIV), 'UY': np.empty(DIV), 'UZ': np.empty(DIV), 'N': np.empty(DIV), 'V': np.empty(DIV), 'M': np.empty(DIV), 'ID_ELEMENT': J_COUNT} for J_COUNT in range(N_ELEMENTS)]
    for J_ELEMENT in range(N_ELEMENTS):
        # ELEMENT PROPERTIES: MATERIAL AND SECTION
        MATERIAL_JELEMENT = FINITO_CL.MATERIALS_PROPERTIES_0(ELEMENTS, MATERIALS, J_ELEMENT, AUX_1)
        SECTION_JELEMENT = FINITO_CL.GEOMETRIC_PROPERTIES_0(COORDINATES, ELEMENTS, SECTIONS, J_ELEMENT, AUX_2)
        # ELEMENT STIFFNESS LOCAL AXIS
        K_JELEMENT = FINITO_CL.ELEMENT_STIFFNESS_0(TYPE_ELEMENT, SECTION_JELEMENT, MATERIAL_JELEMENT, HINGES[J_ELEMENT, :])
        # ROTATION
        R_JELEMENT = FINITO_CL.ELEMENT_ROTATION(TYPE_ELEMENT, SECTION_JELEMENT)
        # GOBAL DOF J_ELEMENT
        DOF_GLOBALJELEMENT = FINITO_CL.GLOBAL_DOF_ELEMENT(N_NODESELEMENT, N_DOFSNODE, DOF_GLOBALNODAL, ELEMENTS, J_ELEMENT)
        # ELEMENT GLOBAL DISPLACEMENTS
        U_GJELEMENT = FINITO_CL.CONDENSE_GLOBAL_ELEMENT_DISPLACEMENTS(U_G, N_DOFSELEMENT, DOF_GLOBALJELEMENT)
        # ELEMENT LOCAL DISPLACEMENTS
        U_JELEMENT = np.dot(R_JELEMENT, U_GJELEMENT)
        # INTERNAL FORCE IN J_ELEMENT (NODE 1 AND NODE 2 [X, Y, Z])
        F_ELINT = np.dot(K_JELEMENT, U_JELEMENT)
        # INTERNAL FORCES IN ELEMENT (DIVISION)
        for I_COUNT in range(DIV):
            # DISTANCE IN LOCAL AXIS
            X = SECTION_JELEMENT[0] * (I_COUNT) / (DIV - 1)
            if I_COUNT == 0:
                U_X = U_GJELEMENT[0, 0]
                U_Y = U_GJELEMENT[1, 0]
                U_Z = U_GJELEMENT[2, 0]
            elif I_COUNT == DIV - 1:
                U_X = U_GJELEMENT[3, 0]
                U_Y = U_GJELEMENT[4, 0]
                U_Z = U_GJELEMENT[5, 0]
            elif (I_COUNT != 0 and I_COUNT != DIV - 1):
                U_X = -1989
                U_Y = -1989
                U_Z = -1989
            # INTERNAL LOADS: AXIAL, SHEAR AND BENDING MOMENT 
            N = -F_ELINT[0]
            V = F_ELINT[1]
            M = -F_ELINT[2] + F_ELINT[1] * X         
            # SAVE RESULTS IN DICTIONARY
            RESULTS[J_ELEMENT]['X'][I_COUNT] = X
            RESULTS[J_ELEMENT]['UX'][I_COUNT] = U_X
            RESULTS[J_ELEMENT]['UY'][I_COUNT] = U_Y
            RESULTS[J_ELEMENT]['UZ'][I_COUNT] = U_Z
            RESULTS[J_ELEMENT]['N'][I_COUNT] = N
            RESULTS[J_ELEMENT]['V'][I_COUNT] = V
            RESULTS[J_ELEMENT]['M'][I_COUNT] = M
    return RESULTS


def MEF2D(**kwargs):
    """ 
    This function performs structural analysis via finite elements 
    considering flat surface elements (CST, LST*, QST*)
    
    * Under development

    Input:
    All inputs kwargs arguments type
    FILENAME: Structural dataset (.txt extension)
    DICTIONARY: Structural dataset (Python dictionary)

    Output:
    RESULTS: Structural analysis results by element (Python dictionary)
    """
    # Read input file
    FILENAME = kwargs.get('FILENAME')
    DICTIONARY = kwargs.get('DICTIONARY')
    if FILENAME:
        [N_NODES, N_MATERIALS, N_THICKNESS, N_ELEMENTST3, N_ELEMENTST6, N_ELEMENTST10, N_FORCES, N_PRESSURES, N_DISPLACEMENTS, TYPE_PLANE, TYPE_ELEMENT, TYPE_SOLUTION, TYPE_INTEGRATION, COORDINATES, MATERIALS, THICKNESS, ELEMENTS, NODAL_EXTERNAL_LOAD, PRESCRIPTIONS] = FINITO_CL.GET_VALUE_FROM_TXT_MEF2D_FINITO(FILENAME)
    else:
        pass
    # Creating the algorithm's internal parameters
    N_DOFSNODE, N_NODESELEMENT, DOFS_ACTIVE, DOFS_LOCAL, AUX_1, AUX_2, N_DOFSELEMENT = FINITO_CL.INDEX_ASSEMBLY(TYPE_ELEMENT)
    # Global DOF assembly
    DOF_GLOBALNODAL = FINITO_CL.DOF_GLOBAL_ASSEMBLY(TYPE_ELEMENT, N_DOFSNODE, N_NODES)
    # DOF's total, prescriptions and free
    DOF_GLOBAL, N_DOFSGLOBAL = FINITO_CL.TOTAL_DEGREE_FREEDOM(N_DOFSNODE, N_NODES)
    DOF_PRESCRIPTIONS, DOF_PRESCRIPTIONSVALUE, N_DOFSPRESCRIPTIONS = FINITO_CL.PRESCRIPTIONS_DEGREE_FREEDOM(PRESCRIPTIONS, DOF_GLOBALNODAL, N_DOFSNODE)
    DOF_FREE, N_DOFSFREE = FINITO_CL.FREE_DEGREE_FREEDOM(DOF_PRESCRIPTIONS, DOF_GLOBAL)
    # Nodal load contribuition
    DOF_NODALFORCE = FINITO_CL.CONTRIBUTION_NODAL_EXTERNAL_LOAD(NODAL_EXTERNAL_LOAD, N_DOFSGLOBAL, DOF_GLOBALNODAL)
    F_EXT = DOF_NODALFORCE
    # Structure stiffness matrix
    K_G = np.zeros((N_DOFSGLOBAL, N_DOFSGLOBAL))
    # Numerical integration properties
    NUM_INT = FINITO_CL.NUMERICAL_INTEGRATION(TYPE_INTEGRATION)
    for I_ELEMENT in range(N_ELEMENTST3):
        # i element properties
        MATERIAL_ID = int(ELEMENTS[I_ELEMENT, 4])
        E = MATERIALS[MATERIAL_ID, 0]
        NU = MATERIALS[MATERIAL_ID, 1]

        if TYPE_PLANE == 1:
            C11 = 1
            C12 = NU
            C21 = C12
            C22 = 1
            C33 = 0.5 * (1 - NU)
            AUX_1 = E / (1 - NU ** 2)
            AUX_2 = np.array([[C11, C12, 0], [C21, C22, 0], [0, 0, C33]])
            Constitutive = AUX_1 * AUX_2
        # Plane strain
        else:
            C11 = 1 - NU
            C12 = NU
            C21 = NU
            C22 = 1 - NU
            C33 = 0.5 - NU
            AUX_1 = E / ((1 + NU) * (1 - 2 * NU))
            AUX_2 = np.array([[C11, C12, 0], [C21, C22, 0], [0, 0, C33]])
            Constitutive = AUX_1 * AUX_2

        # C_IELEMENT = FINITO_CL.CONSTITUTIVE_C(TYPE_PLANE, MATERIALS, ELEMENTS, I_ELEMENT)
        SECTION_IELEMENT = FINITO_CL.GEOMETRIC_PROPERTIES_1(COORDINATES, ELEMENTS, I_ELEMENT, THICKNESS, AUX_2)
        # i stiffness matrix
        # K_IELEMENTGLOBAL = FINITO_CL.ELEMENT_STIFFNESS_1(NUM_INT, N_DOFSELEMENT, TYPE_ELEMENT, N_NODESELEMENT, C_IELEMENT, SECTION_IELEMENT)
        K_IELEMENTGLOBAL = FINITO_CL.ELEMENT_STIFFNESS_1(NUM_INT, N_DOFSELEMENT, TYPE_ELEMENT, N_NODESELEMENT,Constitutive, SECTION_IELEMENT)
        # Global DOF in i element
        DOF_GLOBALIELEMENT = FINITO.GLOBAL_DOF_ELEMENT(N_NODESELEMENT, N_DOFSNODE, DOF_GLOBALNODAL, ELEMENTS, I_ELEMENT)
        K_GCONTRIBUITION = FINITO_CL.GLOBAL_STIFFNESS(N_DOFSGLOBAL, DOF_GLOBALIELEMENT, K_IELEMENTGLOBAL)
        K_G = K_G + K_GCONTRIBUITION


    if TYPE_SOLUTION == 1:
        K_G, FORCE_GLOBAL = FINITO_CL.ZERO_AND_ONE_METHOD(K_G, DOF_NODALFORCE, PRESCRIPTIONS)
        RESULTS = np.linalg.solve(K_G, FORCE_GLOBAL)

    return RESULTS
